import { execSync } from 'child_process';
import { writeFileSync } from 'fs';

export async function createAutoPr(refactoredCode: string, targetFile: string) {
    const c = {
        reset: '\x1b[0m',
        bold: '\x1b[1m',
        dim: '\x1b[2m',
        green: '\x1b[32m',
        red: '\x1b[31m',
        yellow: '\x1b[33m',
        cyan: '\x1b[36m',
    };

    console.log(`\n${c.bold}🚀 Generating Auto-PR for Refactoring...${c.reset}`);

    // Check if gh cli is installed
    try {
        execSync('gh --version', { stdio: 'ignore' });
    } catch {
        console.error(`${c.red}Error: GitHub CLI (gh) is not installed. Please install it to use Auto-PR.${c.reset}`);
        process.exit(1);
    }

    // Check if we have uncommitted changes
    try {
        const status = execSync('git status --porcelain', { encoding: 'utf-8' });
        if (status.trim().length > 0) {
            console.error(`${c.yellow}⚠️  You have uncommitted changes. Please stash or commit them before running Auto-PR.${c.reset}`);
            process.exit(1);
        }
    } catch {
        console.error(`${c.red}Error: Not inside a valid git repository.${c.reset}`);
        process.exit(1);
    }

    const branchName = `prsense/refactor-${Date.now()}`;
    
    try {
        console.log(`${c.dim}Creating branch ${branchName}...${c.reset}`);
        execSync(`git checkout -b ${branchName}`);
        
        // This is a simplified Auto-PR flow. In a real scenario, you would write the refactoredCode
        // to a specific shared utility file, then remove the duplicate blocks from the source files.
        // For the CLI MVP, we'll write it to the targetFile (which could be the first source file or a new utils file).
        
        writeFileSync(targetFile, refactoredCode, 'utf-8');
        
        console.log(`${c.dim}Committing changes to ${targetFile}...${c.reset}`);
        execSync(`git add ${targetFile}`);
        execSync(`git commit -m "refactor: Agentic extraction of duplicate logic via PRSense"`);
        
        console.log(`${c.dim}Pushing branch...${c.reset}`);
        execSync(`git push origin ${branchName}`);
        
        console.log(`${c.dim}Opening Pull Request via GitHub CLI...${c.reset}`);
        const prUrl = execSync(`gh pr create --title "✨ Agentic Refactor: Unified Duplicate Logic" --body "## PRSense Agentic Refactor\nThis PR automatically extracts duplicated logic into a shared utility function inside \`${targetFile}\`.\n\n_Generated by PRSense Refactor Engine v2.2.0_"`, { encoding: 'utf-8' });
        
        console.log(`\n${c.bold}${c.green}✅ Auto-PR created successfully!${c.reset}`);
        console.log(`${c.cyan}${prUrl.trim()}${c.reset}\n`);
        
        // Return to original branch
        execSync('git checkout -');
        
    } catch (err) {
        console.error(`${c.red}Failed to create Auto-PR:${c.reset}`, err instanceof Error ? err.message : String(err));
        // Try to revert
        try { execSync('git checkout -'); } catch {}
        process.exit(1);
    }
}
