import { PRSenseDetector } from './prsense.js'

export interface PRDescriptionInput {
    title: string
    diff: string
    author: string
    files: string[]
}

export class DescriptionGenerator {
    private detector: PRSenseDetector | null

    constructor(detector?: PRSenseDetector) {
        this.detector = detector || null
    }

    /**
     * Set the detector instance if not provided in constructor
     */
    public setDetector(detector: PRSenseDetector) {
        this.detector = detector
    }

    /**
     * Generate an AI-powered PR description based on the diff and historical context.
     * 
     * Since this is PRSense, we focus on identifying what kind of change this is
     * based on patterns we've seen before, without actually calling an LLM 
     * (keeping it local/fast via embeddings/heuristics).
     */
    public async generate(pr: PRDescriptionInput): Promise<string> {
        // 1. Analyze Diff
        const diffLines = pr.diff.split('\n')
        const added = diffLines.filter(l => l.startsWith('+') && !l.startsWith('+++'))
        const removed = diffLines.filter(l => l.startsWith('-') && !l.startsWith('---'))

        let summaryType = 'Refactor'
        if (added.length > removed.length * 2) summaryType = 'Feature'
        if (pr.title.toLowerCase().includes('fix') || pr.title.toLowerCase().includes('bug')) summaryType = 'Bug Fix'
        if (pr.files.some(f => f.endsWith('.md'))) summaryType += ' + Documentation'

        // 2. Fetch Historical Context (similar PRs)
        let relatedText = ''
        if (this.detector) {
            // Find similar PRs to understand context
            const similar = await this.detector.search(pr.title, 3) // get top 3 similar

            if (similar.length > 0) {
                relatedText = `\n### 🔗 Related Historical Changes\nBased on similar code changes in the past, this PR relates to:\n`
                similar.forEach(s => {
                    const conf = Math.round(s.score * 100)
                    relatedText += `- **PR #${s.prId}** (${conf}% similarity)\n`
                })
            }
        }

        // 3. Build Description Template
        const description = `
## 🤖 PRSense Generated Description

### 📋 Summary
**Type:** ${summaryType}
**Author:** @${pr.author}

This PR touches ${pr.files.length} files, with ${added.length} additions and ${removed.length} deletions.

### 🔄 Changes Overview
${pr.files.slice(0, 5).map(f => `- \`${f}\``).join('\n')}
${pr.files.length > 5 ? `- ...and ${pr.files.length - 5} more files` : ''}
${relatedText}
---
*Auto-generated by PRSense v1.1.0*
        `.trim()

        return description
    }
}
