import { PRSenseDetector } from './prsense.js'

export interface PRDescriptionInput {
    title: string
    diff: string
    author: string
    files: string[]
}

/**
 * LLM provider interface for description generation
 */
interface LLMProvider {
    generate(prompt: string): Promise<string>
}

export class DescriptionGenerator {
    private detector: PRSenseDetector | null
    private llm: LLMProvider | null

    constructor(detector?: PRSenseDetector, llm?: LLMProvider) {
        this.detector = detector || null
        this.llm = llm || null
    }

    /**
     * Set the detector instance if not provided in constructor
     */
    public setDetector(detector: PRSenseDetector) {
        this.detector = detector
    }

    /**
     * Set the LLM provider for AI-powered descriptions
     */
    public setLLM(llm: LLMProvider) {
        this.llm = llm
    }

    /**
     * Generate a PR description based on the diff and historical context.
     * 
     * If an LLM is available, uses AI for intelligent summarization.
     * Otherwise falls back to heuristic-based template generation.
     */
    public async generate(pr: PRDescriptionInput): Promise<string> {
        // 1. Analyze Diff
        const diffLines = pr.diff.split('\n')
        const added = diffLines.filter(l => l.startsWith('+') && !l.startsWith('+++'))
        const removed = diffLines.filter(l => l.startsWith('-') && !l.startsWith('---'))

        let summaryType = 'Refactor'
        if (added.length > removed.length * 2) summaryType = 'Feature'
        if (pr.title.toLowerCase().includes('fix') || pr.title.toLowerCase().includes('bug')) summaryType = 'Bug Fix'
        if (pr.files.some(f => f.endsWith('.md'))) summaryType += ' + Documentation'

        // 2. Fetch Historical Context (similar PRs)
        let relatedText = ''
        let relatedContext = ''
        if (this.detector) {
            const similar = await this.detector.search(pr.title, 3)

            if (similar.length > 0) {
                relatedText = `\n### 🔗 Related Historical Changes\nBased on similar code changes in the past, this PR relates to:\n`
                similar.forEach(s => {
                    const conf = Math.round(s.score * 100)
                    relatedText += `- **PR #${s.prId}** (${conf}% similarity)\n`
                })
                relatedContext = similar.map(s => `PR #${s.prId}: ${s.title}`).join('\n')
            }
        }

        // 3. If LLM is available, generate an AI-powered description
        if (this.llm) {
            try {
                const prompt = `You are a senior software engineer writing a concise PR description.

**PR Title:** ${pr.title}
**Author:** ${pr.author}
**Files changed (${pr.files.length}):**
${pr.files.slice(0, 15).map(f => `- ${f}`).join('\n')}
${pr.files.length > 15 ? `...and ${pr.files.length - 15} more files` : ''}

**Change type:** ${summaryType}
**Stats:** ${added.length} additions, ${removed.length} deletions

**Diff (first 3000 chars):**
\`\`\`
${pr.diff.substring(0, 3000)}
\`\`\`

${relatedContext ? `**Related past PRs:**\n${relatedContext}` : ''}

Write a clear, structured PR description with:
1. A one-line summary of what this PR does
2. Key changes (bullet points)
3. Any potential risks or things reviewers should focus on

Keep it concise and professional. Do not include the PR title in the summary.`

                const aiDescription = await this.llm.generate(prompt)

                return `## 🤖 PRSense AI Description

${aiDescription}

---
### 📊 Stats
**Type:** ${summaryType} | **Author:** @${pr.author} | **${pr.files.length}** files, **${added.length}** additions, **${removed.length}** deletions
${relatedText}
---
*Auto-generated by PRSense v2.0.0 (AI-powered)*`.trim()
            } catch (error) {
                console.error('LLM description generation failed, falling back to heuristic:', error)
                // Fall through to heuristic mode
            }
        }

        // 4. Fallback: Heuristic-based template
        const description = `
## 🤖 PRSense Generated Description

### 📋 Summary
**Type:** ${summaryType}
**Author:** @${pr.author}

This PR touches ${pr.files.length} files, with ${added.length} additions and ${removed.length} deletions.

### 🔄 Changes Overview
${pr.files.slice(0, 5).map(f => `- \`${f}\``).join('\n')}
${pr.files.length > 5 ? `- ...and ${pr.files.length - 5} more files` : ''}
${relatedText}
---
*Auto-generated by PRSense v2.0.0*
        `.trim()

        return description
    }
}
